### ISSUE TITLE
lime green in report viz

### ISSUE THREAD

**Issue by RyanSnodgrass** [ndoit/fenrir#134]
Not sure if we are into cosmetics yet....
fwiw, a color choice suggestions.    and please know that color and art is NOT my thing  :-)

but having said that,  I found the light green for staff to be - bam! in your face - in terms of color palate,  I opened it on a large monitor so it really came across loud because of the wide bars.  also it is a different green than the green used above it. 
![unnamed-1](https://cloud.githubusercontent.com/assets/7104855/15290705/528d67fe-1b48-11e6-8f6d-3941cc64b5d2.png)

**Comment by EvanGranthamBrown** [comment]
Changed staff color to dark gray.
