### ISSUE TITLE
Menu Bar - Responsive Issues

### ISSUE THREAD

**Issue by cfreder2** [ndoit/fenrir#135]
@RyanSnodgrass - To fix - Move about into the pancake menu or reduce font size?

![image](https://cloud.githubusercontent.com/assets/407661/15292215/015f7298-1b50-11e6-9148-251ed9481d28.png)

**Comment by RyanSnodgrass** [comment]
Eventually, we'll have these menu items collapse into the hamburger menu

**Comment by cfreder2** [comment]
Closed.  The last release addressed this issue by changing how the menu bar worked.
