### ISSUE TITLE
Offices Page Needs a title, and little blurb of what and why they're seeing

### ISSUE THREAD

**Issue by cfreder2** [ndoit/fenrir#141]
This page is very confusing.  Most users end out here looking for contact information.

At a minimum:

- [x] Add title of office to page
- [x] Add description of why they are seeing these lists of "Related Glossary" terms on the Offices Page
- [x] Add a sentence when there are no terms under a heading, or simply hide that heading.

![image](https://cloud.githubusercontent.com/assets/407661/15294180/3556935c-1b59-11e6-9c56-fab8096f6b72.png)

**Comment by RyanSnodgrass** [comment]
Chris is not an administrator so that's what he's seeing. It's an issue

**Comment by RyanSnodgrass** [comment]
I'll handle this

**Comment by RyanSnodgrass** [comment]
merged into dev branch from PR #157
