### ISSUE TITLE
Page did not load properly

### ISSUE THREAD

**Issue by jasonpcasey** [ndoit/fenrir#148]
Mid session, datasets page failed to load properly. 

See:
![capture](https://cloud.githubusercontent.com/assets/6874881/15295609/4e503632-1b5f-11e6-82fa-1dacf93bd945.PNG)

**Comment by RyanSnodgrass** [comment]
@jasonpcasey which environment was that? We're aware of the datasets not loading in test, but DEV should be operational

**Comment by EvanGranthamBrown** [comment]
Keep in mind that we rebooted DEV several times this morning. It's possible
a reboot interrupted the download. Jason, can you get the issue to happen
again?

**Comment by jasonpcasey** [comment]
My bad.  It was in Test.  Dev works fine.
