### ISSUE TITLE
Research Expenditure Issue

### ISSUE THREAD

**Issue by cfreder2** [ndoit/fenrir#149]
![image](https://cloud.githubusercontent.com/assets/407661/15299290/b4286152-1b71-11e6-9691-9322ac993d3f.png)

**Comment by jasonpcasey** [comment]
No.  There are other types of funds (business, non-profits, etc.).  Federal and Institutional are the two most important to track, which is why they were selected.

**Comment by cfreder2** [comment]
Awesome.  Thanks for the input.
