### ISSUE TITLE
Text description too long for reports - P2

### ISSUE THREAD

**Issue by cfreder2** [ndoit/fenrir#150]
**Medium Priority**
The report description is too long on the report detail page.  Instead of the entire description, can we show one or two lines of text that fades-out with a more button?

bad css example.

![image](https://cloud.githubusercontent.com/assets/407661/15309918/396a9816-1bb9-11e6-9657-d342edfe9674.png)

**Comment by RyanSnodgrass** [comment]
![read_more](https://cloud.githubusercontent.com/assets/7104855/15506094/3678f22a-2194-11e6-9ff4-99582e7d846f.png)
Read more button lines need to match the border color

**Comment by RyanSnodgrass** [comment]
### closed
<img width="1163" alt="readmore-closed" src="https://cloud.githubusercontent.com/assets/7104855/15510619/3c021746-21a6-11e6-966f-041ee9b5e3a6.png">

### open
<img width="1155" alt="readmore-open" src="https://cloud.githubusercontent.com/assets/7104855/15510632/48ab9c06-21a6-11e6-9c3e-017dbf5d66c6.png">
