### ISSUE TITLE
All Reports: Show number in stacked bar charts

### ISSUE THREAD

**Issue by bjaworskiND** [ndoit/fenrir#154]
Feedback from David Bailey on all Reports

- Where possible, it would be great to see the number in the stacked bar charts, not just the label.  There would have to be some way to not show the number or %, if it was low so that it wouldn't block the label (eg. in the bar chart on Research Expenditures by Division when you select Total, or in Comparative Employment).  I know this is a real estate issue/view-ability issue

**Comment by EvanGranthamBrown** [comment]
Not fixing. There is not room on the screen for both category labels and numbers, and the labels are more important. If users need to see the numbers on screen, we should add a table.
