### ISSUE TITLE
Comparative Fall Enrollment/Comparative Employment Reports: Headcount Option

### ISSUE THREAD

**Issue by EvanGranthamBrown** [ndoit/fenrir#162]
Feedback from David Bailey on the Comparative Fall Enrollment and Comparative Employment reports:

If you select Female, or US Minority, or International, can we see % of total (as it is shown now) AND an option to see the number in the Bar Chart and Box Plot (i.e., our number of T-TT faculty versus the AAU privates)? This option is available in the Research Expenditures report when you select Federal Funds or Institutional Funds.

**Comment by CaelaKleber** [comment]
This is done for the Comparative Fall Enrollment Report. Working on the Employment Report next.

**Comment by CaelaKleber** [comment]
This is done for both reports but not published yet.
