### ISSUE TITLE
Research Expenditures Report: Stacked Bar by Source?

### ISSUE THREAD

**Issue by EvanGranthamBrown** [ndoit/fenrir#163]
Feedback from David Bailey:

Should we add a stacked bar chart that has ND-only Expenditures by source for all categories (Federal, Institutional, etc.) in addition to the line chart if you select Total Expenditures - similar to what we have on the Research Expenditures by Division Report?

**Comment by EvanGranthamBrown** [comment]
I realized this is a different question from what we discussed on Res Exp by Division. The regular Research Expenditures report is showing sources already, so it might make sense to break those sources down further. On the other hand, do we even have that level of detail in the Institutions dataset?

If the data exist, this is probably worth at least trying out. If the data aren't there, of course, there's nothing more to do.

**Comment by CaelaKleber** [comment]
We do have source data in the Institutions dataset, but the expenditures for each source are in separate fields (unlike the division dataset which just has one funding source field). So we wouldn't be able to do stacked bars, unfortunately, at least not without a lot of work to manipulate the data. I can think about alternative ways to display this data but I'm not sure if it will be worth the effort.

**Comment by smathewsnd** [comment]
too much effort for the value at this point.
