### ISSUE TITLE
dataND does not render correctly in IE

### ISSUE THREAD

**Issue by bjaworskiND** [ndoit/fenrir#165]
Need to support IE v11

**Comment by bjaworskiND** [comment]
IE v11 cuts off dataND logo (upper left) and University of Notre Dame logo (bottom right)

![image](https://cloud.githubusercontent.com/assets/19391188/15398499/d5ed4716-1db1-11e6-97f6-f2b6a7baf516.png)

**Comment by bjaworskiND** [comment]
downgrading to a P2 because IE v11 looks good except for the 2 logos.  Functionally, site looks good.

**Comment by smathewsnd** [comment]
this is closed from #178
