### ISSUE TITLE
Replace "Non-existent user" with user friendly verbiage 

### ISSUE THREAD

**Issue by bjaworskiND** [ndoit/fenrir#167]
When a user logs in, but their account doesn't exist in the Graph DB, instead of displaying "Non-existent user" in the menu....replace with a more user friendly experience.  Additionally, if possible, provide some mechanism in which we can track these instances so the user can be added the Graph DB.

**Comment by RyanSnodgrass** [comment]
trying this out?
![nonexistant user](https://cloud.githubusercontent.com/assets/7104855/15370368/b68146aa-1d04-11e6-9762-9f35d7dcc46b.png)

**Comment by RyanSnodgrass** [comment]
or how about this?
![non existant user with guest](https://cloud.githubusercontent.com/assets/7104855/15370485/4372f770-1d05-11e6-9b27-4239cf7cadb0.png)

**Comment by RyanSnodgrass** [comment]
@bjaworskiND "Would it be an option to show just the netID and then have an FAQ...."Why can't I see datasets and reports?"  The answer can then reflect either a permission thing or a missing account in the Graph DB????"

**Comment by RyanSnodgrass** [comment]
@jdosmann "jdosmann (GUEST)"

**Comment by RyanSnodgrass** [comment]
![nonexistant user guest simple](https://cloud.githubusercontent.com/assets/7104855/15370707/22bfcd9a-1d06-11e6-8346-0db813f064ec.png)
That would be all it says, I can link it to a page on aboudata.nd.edu
