### ISSUE TITLE
Buttons are different sizes

### ISSUE THREAD

**Issue by cfreder2** [ndoit/fenrir#180]
![image](https://cloud.githubusercontent.com/assets/407661/15406812/fa4dee52-1dd5-11e6-9d0e-b68b239f9ee3.png)

**Comment by RyanSnodgrass** [comment]
@EvanGranthamBrown already added something to change the height of the buttons

**Comment by RyanSnodgrass** [comment]
Not quite fixed. Doesn't set anything as a default. the default buttons have no height settings

**Comment by RyanSnodgrass** [comment]
Closing already in master
