### ISSUE TITLE
Gracefully handle user without EDW access

### ISSUE THREAD

**Issue by EvanGranthamBrown** [ndoit/fenrir#183]
If a user doesn't have access to the EDW (e.g., a new user whose accounts are not all set up yet), we should provide a helpful error message instead of a nasty SQL error.

Also, we should make sure we're never showing nasty SQL errors; it's a (minor) security risk.

**Comment by smathewsnd** [comment]
don't have account or don't have permission errors

**Comment by EvanGranthamBrown** [comment]
Superseded by datasets 3.0.
