### ISSUE TITLE
UX: Soften "download" to Tableau

### ISSUE THREAD

**Issue by cfreder2** [ndoit/fenrir#185]
![image](https://cloud.githubusercontent.com/assets/407661/15408413/1e0609c6-1dde-11e6-982d-fbe8300818e8.png)

**Comment by jdosmann** [comment]
Web Edit is out for 6/6.

*Joel Dosmann*

Business Intelligence
The Office of Information Technologies
University of Notre Dame
200A IT Center | Notre Dame, IN 46556
P: (574) 631-5620
jdosmann@nd.edu

**Comment by smathewsnd** [comment]
closed based on Marcomm's suggestion.
