### ISSUE TITLE
Partial word search not working

### ISSUE THREAD

**Issue by cfreder2** [ndoit/fenrir#188]
When you type ahead you see results.  

Try typing "Empl", you see:
![image](https://cloud.githubusercontent.com/assets/407661/15408809/0ce30f84-1de0-11e6-894a-d98a880c67d7.png)

When you hit enter you see:
![image](https://cloud.githubusercontent.com/assets/407661/15408822/1e2b2a10-1de0-11e6-89bc-1726264f958f.png)

**Comment by RyanSnodgrass** [comment]
this should be easy to implement from the [searchkick gem](https://github.com/ankane/searchkick#partial-matches)
