### ISSUE TITLE
UX: Report load is slow and awkward

### ISSUE THREAD

**Issue by cfreder2** [ndoit/fenrir#190]
Users are confused when report is loading via ajax.  Can we replace the report div with a loading div until the tableau report is loaded?

![image](https://cloud.githubusercontent.com/assets/407661/15429052/c99ae0b6-1e6c-11e6-8feb-c985168442f7.png)

**Comment by smathewsnd** [comment]
Add a different mechanism(interlocking image loader) from Jacob Scooner. Chris will be co-ordinate the effort.

**Comment by smathewsnd** [comment]
Re-opening the issue

**Comment by smathewsnd** [comment]
This issue is fixed by using tableau a trusted authenticated server setup
