### ISSUE TITLE
Printing Reports Does Not Work

### ISSUE THREAD

**Issue by EvanGranthamBrown** [ndoit/fenrir#212]
Go to a report page, try to print it, and observe the horrible mess that results.

**Comment by smathewsnd** [comment]
6/6 - add an explanation that printing feature is unavailable for this release.(about.nd.edu)

**Comment by ssporins** [comment]
the aboutdata.nd.edu piece is now done.

aboutdata.nd.edu now includes a reference to this challenge of printing a report.   It indicates this is a temporary situation and offers suggestions for what to do "in the meantime".
