### ISSUE TITLE
Browser Processing Error on report detail page

### ISSUE THREAD

**Issue by bjaworskiND** [ndoit/fenrir#213]
When accessing the Comparative Employment report, the reports loaded but I received "Browser Processing Error" messages throughout the page.

![image](https://cloud.githubusercontent.com/assets/19391188/15551180/d5b6717a-2282-11e6-83c6-ab8bb031dd00.png)

**Comment by jdosmann** [comment]
I believe this was a network drop based on some searching the error message
and that it isn't repeatable.  Let's keep an eye on it...

*Joel Dosmann*

Business Intelligence
The Office of Information Technologies
University of Notre Dame
200A IT Center | Notre Dame, IN 46556
P: (574) 631-5620
jdosmann@nd.edu

**Comment by smathewsnd** [comment]
difficult to re-create. If it happens again will re-open.
