### ISSUE TITLE
Changing sort order on report jumbles up report text

### ISSUE THREAD

**Issue by bjaworskiND** [ndoit/fenrir#214]
For the Growth:Employees report, I clicked on the Y axis and then clicked the "descending" icon to sort the graph descending vs. ascending but the text got all messed up. 

![image](https://cloud.githubusercontent.com/assets/19391188/15551561/8e5c1df0-2284-11e6-8ee7-3534d7edd98b.png)

**Comment by cfreder2** [comment]
Tableau issue, not much we can do.
