### ISSUE TITLE
Hamburger menu selection does not collapse

### ISSUE THREAD

**Issue by mbennitt** [ndoit/fenrir#215]
After making a selection within the hamburger menu, the menu does not auto-collapse.

![image](https://cloud.githubusercontent.com/assets/18443318/15551786/889ab7a4-2285-11e6-9921-d3e0f464dfcd.png)

![image](https://cloud.githubusercontent.com/assets/18443318/15551806/a27ba07a-2285-11e6-9ee1-c39f29fe6d3a.png)

**Comment by RyanSnodgrass** [comment]
This happens when the user is already on the search index page

**Comment by RyanSnodgrass** [comment]
https://codepen.io/designcouch/pen/Atyop
