### ISSUE TITLE
home page hamburger, how do I get back to normal view.

### ISSUE THREAD

**Issue by ssporins** [ndoit/fenrir#219]
it is unclear, after clicking on hamburger, how to get screen back to normal.

**Comment by RyanSnodgrass** [comment]
clicking anywhere greyed out on the screen closes the hamburger. This is expected behavior for all off canvas style navagation. Maybe can add a X to the hamburger to indicate you can click there to close?

**Comment by ssporins** [comment]
It may help us to look at how other sites handle this.
