### ISSUE TITLE
search list is deceiving

### ISSUE THREAD

**Issue by ssporins** [ndoit/fenrir#223]
when I enter a search word into the text search box, I get a list.    testing instructions tell me to hit "enter" and then I see an even larger list with more choices.   this is very confuing and how would the user know to press "enter"?

**Comment by RyanSnodgrass** [comment]
The user would know because that's how nearly every search engine works

**Comment by RyanSnodgrass** [comment]
from google, to bing, to amazon, netflix, yahoo, metacrawler, duckduckgo, every search engine i can think of has the ability to hit enter to search more. Considering closing this one.

**Comment by RyanSnodgrass** [comment]
Bing doesn't even tell you to press enter.

**Comment by ssporins** [comment]
No objection.   And hey..  Bing ain't That bad!

**Comment by cfreder2** [comment]
I'm closing this issue.
