### ISSUE TITLE
search.  datasets shows other choices that aren't datasets

### ISSUE THREAD

**Issue by ssporins** [ndoit/fenrir#224]
if I go to "datasets" in the upper right of dataND.  and then do search, I expected to see my search target just datasets.  instead I see reports and terms, too.   why bother clicking on datasets, then???

**Comment by RyanSnodgrass** [comment]
This is an issue concerning the constant "search all" of the search bar. eventually, we will have the users filtering

**Comment by smathewsnd** [comment]
This is a future enhancement.
