### ISSUE TITLE
dataset view => glossary lookup does not return back to dataset view.

### ISSUE THREAD

**Issue by ssporins** [ndoit/fenrir#229]
open a dataset
wile you are there, you decided you wanted to look up the definition of a term.  so you go to glossary.
now that you've read the definition, you want to go back to the page you were just on.  so you hit back button.   it works if I do multipl "back" clicks.   the back button behavior seems to require double clicks sometimes, but no others.

**Comment by jasonpcasey** [comment]
This is a test.  Seeing what happens when a reply is made to an issue in github.

Jason

**Comment by cfreder2** [comment]
closed, this has been fixed.
