### ISSUE TITLE
Notre Dame logo needs to open a new tab

### ISSUE THREAD

**Issue by bjaworskiND** [ndoit/fenrir#239]
Per Todd Hill from UAT:

UND Logo link at bottom right of all pages should open nd.edu in a new tab, like all of the other external site links.

**Comment by RyanSnodgrass** [comment]
Might be unexpected behavior anyway as no other ND site opens those links in new tabs.

**Comment by smathewsnd** [comment]
This is inconsistent with the current applications of Notre Dame. So team decided to close this case without making any changes to this.
