### ISSUE TITLE
going from report => dataset then "back" button causes report to not redraw. 

### ISSUE THREAD

**Issue by ssporins** [ndoit/fenrir#249]
user opens a comparative report, for example employment.
user decides they want the data set so they click on it at bottom of page.
user views dataset decides they no longer need it:  uses browser's "back button" expecting to go back to the report view.
report does not redraw.  
page seems to hang with fluctuating ND logo.

**Comment by EvanGranthamBrown** [comment]
This appears to be due to browser caching: The browser is caching the results of /tableau/ticketize instead of repeating the AJAX call each time. I've got this.

**Comment by ssporins** [comment]
I believe you are on the right track becuase going "back" once more to the
reports screen and reclicking it generates the report.

**Comment by cfreder2** [comment]
Looks like this is fixed now.  Closing it.
