### ISSUE TITLE
duplicate term?

### ISSUE THREAD

**Issue by cfreder2** [ndoit/fenrir#305]
![image](https://cloud.githubusercontent.com/assets/407661/18522304/82b727b4-7a7d-11e6-9456-e8fb67e7c65a.png)

**Comment by RyanSnodgrass** [comment]
Found only one of such terms in database - therefore Search is broken on this issue

**Comment by RyanSnodgrass** [comment]
Fixed by blowing away search index `curl -XDELETE 'http://localhost:9200/_all'`

Then reindexing all models

**Comment by RyanSnodgrass** [comment]
Cause unknown
