### ISSUE TITLE
Do not allow Illegal characters in report, term, datasets, etc titles

### ISSUE THREAD

**Issue by ssporins** [ndoit/fenrir#317]
Tried to build a report title called "Buildings/Space - ..."
The "/" gets acted upon as if it is a code element throwing an error.
Can we escape the "/" or use an ascii code that would allow a char like this to be used in report title?

**Comment by EvanGranthamBrown** [comment]
In theory, this would be a good idea. In practice, this would require substantial rework; we may tackle it eventually, but not in this release.

**Comment by RyanSnodgrass** [comment]
Ideally we would use javascript to prevent the user from imputing anything other than alpha numerics and `_` and `-`
