### ISSUE TITLE
Glossary needs to expand to relevant terms, not just governed terms.

### ISSUE THREAD

**Issue by ssporins** [ndoit/fenrir#319]
Tried to search on HEGIS.  Got no hit in glossary.  Yet it would handy to list the HEGIS categories and codes there.   vs searching each term.

**Comment by RyanSnodgrass** [comment]
Did you create a "HEGIS" term?

**Comment by cfreder2** [comment]
The issue here is that the word "HEGIS" is not written any where in the definition of "Space Use Code" or "Space Use Category".  If this key word were included in the description then this would not be an issue.  I am closing this issue and I'll send Augie a note.
