### ISSUE TITLE
Admin - Better Layout and Documentation

### ISSUE THREAD

**Issue by cfreder2** [ndoit/fenrir#338]
The Admin Page has grown dramatically with the first release of IronMan.  

Making sure that we maintain the correct data flowing into the EDW is critical to help build confidence in the system.  It is important that the entire BI Team, the Campus Data Steward, and key stakeholders such as OSPIR can use this page to understand the administrative functions needed to run dataND.

In general, this page needs a new layout to help users better understand the tasks.

We need to do the following:

**Create a section that fully documents each nightly job**
- Each step in the job should be clearly identified as a row in the table with the following rows:
  - The job name
  - A plain english description this job
  - A link that opens the logfile that outlines all the details of the job
  - A status of the last run (success / failure), the date of the last run
  - A link to reschedule the job for another time.
  - A link to manually run this step

**Deserialize JSON Nodes**
- Use this feature to import a specific report, term, and dataset between environments.   '
- For example, you can go to to get the json you want to import: 
  - https://<server>/terms/4-Year%20Graduation%20Rate.json
  - https://<server>reports/Comparative%20Employees%20by%20Assigned%20Position.json
  - https://<server>/datasets/Assignable%20Space%20Dataset.json

**Positions to Tables**
- We do not support "deny".  This should be removed from documentation.

**Admin Users**
- Add a way to add/remove/list admin users

**Import Positions to Orgs**
- Remove the export button that provides one row per position with the comma separated list.

**Comment by RyanSnodgrass** [comment]
Done by several pull requests by @smathewsnd
