### ISSUE TITLE
Upgrade Components

### ISSUE THREAD

**Issue by EvanGranthamBrown** [ndoit/fenrir#359]
We need to make the following upgrades:

Ruby 2.2
Rails 4.2
ActiveNode 7.1
Paperclip ?? (figure out what's causing deprecation warnings and fix it)

**Comment by cfreder2** [comment]
ActiveNode running 7.2

**Comment by smathewsnd** [comment]
**Already in Production**
  - Ruby Version - 2.2.5p319
  - Rails Version - 4.2.7.1
**In the next release**
Added a monkey patch to avoid the mistaken depreciation warning.
