### ISSUE TITLE
Technical Debt - Kill and restart Sidekiq

### ISSUE THREAD

**Issue by EvanGranthamBrown** [ndoit/fenrir#360]
We need a way for admins to kill and restart Sidekiq, without having to remote into the box.

**Comment by cfreder2** [comment]
Evan, is this complete or still necessary?  I see that sidekiq.rb has some code that looks to find the process... not sure it kills it though.

**Comment by EvanGranthamBrown** [comment]
Still necessary. We have code that starts up Sidekiq if it isn't running, but we don't have any way to kill it except by remoting into the box.

**Comment by EvanGranthamBrown** [comment]
Done, finally.
