### ISSUE TITLE
Tableau Workbook download opening in browser

### ISSUE THREAD

**Issue by jdosmann** [ndoit/fenrir#367]
On Andrew Sama's pc when he clicks to download the Tableau Workbook, it opens it in his browser instead of starting to download the workbook.  

Browser: Chrome
url displayed: https://tableau.nd.edu/workbooks/Assignable-Space-Template.twb?:embed=y

I believe it is a browser setting that needs tweeked. Any ideas?

**Comment by RyanSnodgrass** [comment]
That is a machine preference. The most we can do is educate and teach people why it happens and what to do.

**Comment by EvanGranthamBrown** [comment]
Ideally, the workbook would always open in the browser, people could make changes using web Tableau, and then save a copy into some kind of "my stuff" folder. It's the last bit that presents a challenge.

**Comment by cfreder2** [comment]
Closing this issue.  I'm not able to reproduce it any longer.  If it comes up again we can identify a solution.
