### ISSUE TITLE
Tableau Workbook Downloads: Help Users Authenticate

### ISSUE THREAD

**Issue by EvanGranthamBrown** [ndoit/fenrir#368]
Need some kind of guidance/assistance for users who download Tableau workbooks. When Tableau fails 2-factor auth, it doesn't open up a dialog box to authenticate--it displays an ugly error message instead. If we can't figure out how to prevent this, we need a way to help users through it.

**Comment by cfreder2** [comment]
Closing this for now as it appears the dialog box to authenticate is slightly better in newer versions of Tableau.
