### ISSUE TITLE
Excel Automatically converting certain text fields to dates when it's not

### ISSUE THREAD

**Issue by smathewsnd** [ndoit/fenrir#442]
In `Assignable Space` dataset certain fields as Room # has valid data like 2-2 or 10-23. 

Excel evaluates these fields as date. Is there a way to bring these elements as `text` than `general` where applicable to avoid this issue?

**Comment by EvanGranthamBrown** [comment]
Only solution I can think of is to download the CSV on the server side, run it through some kind of processor to convert it to XLS, and then serve up the XLS to the user.

**Comment by EvanGranthamBrown** [comment]
I am officially answering my own question: No, it is not worth the bother. If it's critical on a given worksheet, use a formula to put the string in a non-datelike format (e.g., "#10-01" instead of "10-01").
