### ISSUE TITLE
Pivot Preview Table in Datasets

### ISSUE THREAD

**Issue by RyanSnodgrass** [ndoit/fenrir#478]
Tables are gross as they are now. Users have to scroll horizontally to see all the column headers.
<img width="1244" alt="datand_horizontal_preview_table" src="https://cloud.githubusercontent.com/assets/7104855/23219090/1c4dcfc6-f8ec-11e6-8062-3bec3ec7bbcb.png">

Pivot the preview table 90 degrees and have the column headers run down the page.

<img width="505" alt="screen shot 2017-02-22 at 10 47 54 am" src="https://cloud.githubusercontent.com/assets/7104855/23219179/65d0eef8-f8ec-11e6-9b54-b00512dc1f41.png">

**Comment by EvanGranthamBrown** [comment]
Superseded by datasets 3.0.
