### ISSUE TITLE
Pending rspec test for load_from_sql_job

### ISSUE THREAD

**Issue by RyanSnodgrass** [ndoit/fenrir#484]
In `spec/jobs/load_from_sql_job_spec.rb`has a pending test "_accurately reports results_" that has been hanging around for months.

**Comment by RyanSnodgrass** [comment]
@EvanGranthamBrown

**Comment by EvanGranthamBrown** [comment]
Actually not a problem with the test; the test is correctly reporting a (very minor) bug.
